---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: node-feature-discovery
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.17.3
  url: oci://ghcr.io/astrateam-net/oci-charts/node-feature-discovery
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/astrateam-net/oci-charts.*$"
---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: node-feature-discovery
  maxHistory: 2
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    worker:
      config:
        core:
          sources: ["custom", "pci", "usb", "kernel"]
        sources:
          usb:
            deviceClassWhitelist: ["02", "03", "0e", "ef", "fe", "ff"]
            deviceLabelFields: ["class", "vendor", "device"]
          pci:
            deviceClassWhitelist: ["02", "0200", "0207", "0300", "0302"]
            deviceLabelFields: ["vendor"]
      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          memory: 64M
    prometheus:
      enable: true
