---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-postgres17
spec:
  cluster:
    name: postgres17
  instances: 1
  type: "rw"
  serviceTemplate:
    metadata:
      labels:
        app: pooler
    spec:
      type: LoadBalancer
      loadBalancerIP: 10.0.130.20
  monitoring:
    enablePodMonitor: true
  pgbouncer:
    poolMode: "session"
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"