---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/postgresql.cnpg.io/pooler_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-pg17
spec:
  cluster:
    name: postgres17
  instances: 1
  type: "rw"
  serviceTemplate:
    metadata:
      labels:
        app: pooler
      annotations:
        external-dns.alpha.kubernetes.io/hostname: postgres.mrk.am
    spec:
      type: LoadBalancer
      loadBalancerIP: 10.0.130.20
  monitoring:
    enablePodMonitor: true
  pgbouncer:
    poolMode: "session"
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"