---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
components:
  - ../../components/common
resources:
  - ./pdf-tool/ks.yaml
  - ./omi-tools/ks.yaml
  - ./n8n/ks.yaml
  - ./it-tools/ks.yaml