---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app wiki
  namespace: &namespace docs
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/cnpg
    - ../../../../components/gatus/external
    - ../../../../components/volsync
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: database
  interval: 30m
  path: ./kubernetes/apps/docs/wiki/app
  postBuild:
    substitute:
      APP: *app
      GATUS_STATUS: '404'
      VOLSYNC_CAPACITY: 5Gi
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false

