---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghost-app
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ghost-app-secret
    template:
      data:
        username: "{{ .ghost_mysql_username }}"
        password: "{{ .ghost_mysql_password }}"
        # host: "{{ .ghost-db-host }}"
        db: "{{ .ghost_mysql_username }}"
        mail_from: "{{ .ghost_mail_from }}"
        mail_user: "{{ .ghost_mail_user }}"
        mail_pass: "{{ .ghost_mail_pass }}"
        mailgun_api_key: "{{ .mailgun_api_key }}"
  dataFrom:
    - extract:
        key: mysql-innodbcluster-hlab
    - extract:
        key: ghost-app
    - extract:
        key: Mailgun
---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: git-config
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: git-config-secret
    template:
      data:
        .gitconfig: |
          [user]
            name = {{ .ghost_git_name }}
            email = {{ .ghost_git_email }}
        id_rsa: |
          {{ .ghost_git_private_key }}
        known_hosts: |
          github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
        config: |
          Host github.com
            StrictHostKeyChecking no
            UserKnownHostsFile /home/node/.ssh/known_hosts
  dataFrom:
    - extract:
        key: ghost-app