---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ghost-theme-builder
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      ghost-theme-builder:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/astrateam-net/ghost
              tag: 5.123.0@sha256:6d7ae4b4a52f3e33f14f5c88792a2f723c9392034550dd28804f7b61a9d2b963
            env: &env
              TZ: Europe/Moscow
              url: "https://blog.mrk.am"
              NODE_ENV: development
              database__client: mysql
              database__connection__host: mysql-innodbcluster.database.svc.cluster.local
              database__connection__user:
                valueFrom:
                  secretKeyRef:
                    name: &secret ghost-app-secret
                    key: username
              database__connection__password:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: password
              database__connection__database:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: db
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 5m
                memory: 50Mi
              limits:
                memory: 500Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 2368

    route:
      app:
        hostnames:
          - "blog-dev.mrk.am"
        parentRefs:
          - name: external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      content:
        enabled: true
        globalMounts:
          - path: /var/lib/ghost/content
        existingClaim: ghost-theme-builder
      git-config:
        type: secret
        name: git-config-secret
        globalMounts:
          - path: /home/node/.gitconfig
            subPath: .gitconfig
            readOnly: true
          - path: /home/node/.ssh/id_rsa
            subPath: id_rsa
            readOnly: true
          - path: /home/node/.ssh/known_hosts
            subPath: known_hosts
            readOnly: true
          - path: /home/node/.ssh/config
            subPath: config
            readOnly: true