- Social:
    - Discord:
        - icon: discord.png
          href: https://discord.com/app
    - Gmail:
        - icon: gmail.png
          href: http://gmail.com
    - Reddit:
        - icon: reddit.png
          href: https://reddit.com
    - Twitch:
        - icon: twitch.png
          href: https://twitch.tv
    - YouTube:
        - icon: youtube.png
          href: https://youtube.com/feed/subscriptions
- Cloud:
    - CloudFlare:
        - icon: cloudflare.png
          href: https://dash.cloudflare.com
    - AWS Console:
        - icon: aws.png
          href: https://aws.amazon.com/console/
    - Pushover:
        - icon: pushover.png
          href: https://client.pushover.net/
    - UptimeRobot:
        - icon: si-statuspage
          href: https://uptimerobot.com/
    - HealthChecks:
        - icon: healthchecks.png
          href: https://healthcheck.io/
- Git:
    - Kubesearch:
        - icon: kubernetes-dashboard.png
          description: Helm Chart Search
          href: https://nanne.dev/k8s-at-home-search/
    - home-cluster:
        - icon: github.png
          description: Renovate Dashboard
          href: https://github.com/mchestr/home-cluster/issues/2976
    - Homepage Icons:
        - icon: si-jpeg
          href: https://github.com/homarr-labs/dashboard-icons/blob/main/ICONS.md
    - Homepage MDI:
        - icon: si-materialdesign
          href: https://pictogrammers.com/library/mdi/
    - Homepage SI:
        - icon: si-simpleicons
          href: https://simpleicons.org/
    - Armtek:
        - icon: si-simpleicons
          href: https://etp.armtek.ru/
