---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-db-backup-pvc
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 30Gi
  storageClassName: nfs-slow
