---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ntfy
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 2
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
    controllers:
      ntfy:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            args: ["serve"]
            image:
              repository: binwiederhier/ntfy
              tag: v2.12.0
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 256Mi
    service:
      app:
        controller: ntfy
        ports:
          http:
            port: &port 8080
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.mrk.am"
          - sh.mrk.am
        parentRefs:
          - name: external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      config:
        type: configMap
        name: ntfy-server-config
        globalMounts:
          - path: /etc/ntfy/server.yml
            subPath: server.yml
            readOnly: true
      cache:
        type: emptyDir
        globalMounts:
          - path: /var/cache/ntfy
      auth:
        enabled: true
        existingClaim: *app
        advancedMounts:
          ntfy:
            app:
              - path: /authfile