---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pdf-tool
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  install:
    # createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/stirling-tools/s-pdf
              tag: 0.46.2@sha256:396ca949b81198a65b9abfec38518fa44e871b1970dad9f9718ffd030eef9b92
              pullPolicy: IfNotPresent
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 8080
    route:
      internal:
        hostnames: ["{{ .Release.Name }}.mrk.am"]
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *port
    persistence:
      config:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /configs
      tessdata:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /usr/share/tessdata
