---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: promtail
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 6.17.0
  url: oci://ghcr.io/grafana/helm-charts/promtail
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: promtail
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: promtail
    image:
      # # -- The Docker registry
      registry: docker.io
      # # -- Docker image repository
      repository: grafana/promtail
      # # -- Overrides the image tag whose default is the chart's appVersion
      tag: latest-amd64@sha256:7796bd5ae600370ef47e58901310c91e60dc15eb13a3b2e20f1a940cb2777a57
      # # -- Docker image pull policy
      pullPolicy: Always
    config:
      clients:
        - url: http://loki-headless.observability.svc.cluster.local:3100/loki/api/v1/push
    serviceMonitor:
      enabled: true
