---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mikrotik-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mikrotik-dns-secret
    template:
      data:
        MIKROTIK_BASEURL: "{{ .MIKROTIK_BASEURL }}"
        MIKROTIK_USERNAME: "{{ .MIKROTIK_USERNAME }}"
        MIKROTIK_PASSWORD: "{{ .MIKROTIK_PASSWORD }}"
        MIKROTIK_SKIP_TLS_VERIFY: "{{ .MIKROTIK_SKIP_TLS_VERIFY }}"

  dataFrom:
    - extract:
        key: mikrotik
