---
# yaml-language-server: $schema=https://k8s-validation-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mrk-am
spec:
  secretName: mrk-am-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: mrk.am
  dnsNames: ["mrk.am", "*.mrk.am"]
